TodoAdd API 를 수정하라
growth-ring/taskgrow pull request #54
Opened 2023-09-18 09:38 UTC by caoyu-dev

- [ ] TodoAddControllerTest 가 날아가서 다시 작성

2023-09-18 14:41 UTC, kyuwon53 commented on app-server/src/main/java/com/growth/task/todo/dto/composite/TodoAndPomodoroAddRequest.java
> +            @JsonProperty("plan_count") int planCount
![image](https://github.com/growth-ring/taskgrow/assets/86951640/db9aeed7-b896-4178-9d87-6fb09ff0d8b6)

![image](https://github.com/growth-ring/taskgrow/assets/86951640/652144d5-a918-4d0e-853c-50e11704ba5c)

Todo와 Pomodoro를 나누고 싶으신거라면 필드네임을 todo, pomodoro로 하는게 좋을거 같아요. 
```java
    @Valid
    private TodoAddRequest todo;

    @Valid
    private PomodoroAddRequest pomodoro;
```
![image](https://github.com/growth-ring/taskgrow/assets/86951640/d8b3cdda-b974-40f2-a1a3-25eaf69fecaf)

내부 로직에서 사용하기 위해 객체로 두신거라면, 
```java
    @Valid
    @JsonIgnore
    private TodoAddRequest todos;

    @Valid
    @JsonIgnore
    private PomodoroAddRequest pomodoro;
```
직렬화를 안시키게 하는 방법도 있습니다. 
 request는 클라이언트가 그렇게 요청안하면 되겠지만 api 명세인 swagger 예시에 그렇게 나올 것이고, reponse는 PomodoroAddResponse 객체가 그대로 직렬화되어 보일 것입니다. 

![image](https://github.com/growth-ring/taskgrow/assets/86951640/d3c5cf61-5e0a-41dd-a8a5-45b00f634001)

![image](https://github.com/growth-ring/taskgrow/assets/86951640/d0606304-c188-4dec-af18-d488129108cf)

2023-09-18 14:41 UTC, kyuwon53 commented on app-server/src/test/java/com/growth/task/todo/controller/TodoAddControllerTest.java
> +        when(todoAddService.save(Mockito.any(TodoAndPomodoroAddRequest.class))).thenReturn(response);
저는 모킹 테스트를 비선호하는데 그 이유가 원하는 결과를 리턴하기 때문에 실질적인 데이터 출입 테스트가 되지 않는 경우가 많습니다. 테스트는 분명히 통과했는데, QA를 해보면 우수수수 깨지죠. 그게 모킹 테스트는 인풋 아웃풋을 정해두기 때문이에요. 

위의 taskAddRequest의 toEntity에서 status를 넣어주지 않기 때문에 실질 테스트에서는 status가 null이어서 DB 에러가 발생했을 것입니다. 하지만 reponse에서 설정해두고 그렇게 반환한다고 가정하자! 라고 했기때문에 테스트가 깨지지 않죠. 실제 API 요청을 하면 
![image](https://github.com/growth-ring/taskgrow/assets/86951640/3bffd40c-a028-4525-aeed-923eb704f22c)
다음과 같은 에러가 발생합니다.

2023-09-18 15:33 UTC, caoyu-dev commented on app-server/src/main/java/com/growth/task/todo/dto/composite/TodoAndPomodoroAddRequest.java
> +            @JsonProperty("plan_count") int planCount
TodoAndPomodoroAddRequest 에 `@JsonIgnore` 를 적용했습니다. 감사합니다 !
Response 스웨거 페이지의 Response body 는 어찌할지 고민 좀 해보겠습니다.

제 스웨거 페이지가 현재 보이지 않아서 main 을 다시 당겨봐야 할 것 같아요.

2023-09-18 16:04 UTC, caoyu-dev commented on app-server/src/main/java/com/growth/task/todo/dto/request/TodoAddRequest.java
>                  .build();
감사합니다 👍

2023-09-18 23:19 UTC, kyuwon53 commented
<img width="899" alt="image" src="https://github.com/growth-ring/taskgrow/assets/86951640/8238b871-4f53-43e0-b596-5db676a4e91a">
커밋 메시지가 짤렸네요 🤔 뭘 유지했을까....궁금해지는

2023-09-18 23:19 UTC, kyuwon53 requested changes

2023-09-18 23:19 UTC, kyuwon53 commented on app-server/src/test/java/com/growth/task/todo/application/TodoAddServiceTest.java
> +import static org.mockito.Mockito.*;
[IntelliJ Auto import *처리 방지](https://giantdwarf.tistory.com/58)
import 가 * 처리 되었습니다

2023-09-19 06:27 UTC, caoyu-dev commented
> <img alt="image" width="899" src="https://user-images.githubusercontent.com/86951640/268794843-8238b871-4f53-43e0-b596-5db676a4e91a.png"> 커밋 메시지가 짤렸네요 🤔 뭘 유지했을까....궁금해지는

`@JsonIgnore` 를 유지하면서, 직렬화될 추가적인 정보를 유지하기 위해 직렬화 전용 getter 를 추가해라 
입니다 ! commit -m 에서 작성했는데 `@JsonIgnore` 가 잘렸네요 !

2023-09-19 06:28 UTC, caoyu-dev commented on app-server/src/test/java/com/growth/task/todo/application/TodoAddServiceTest.java
> +import static org.mockito.Mockito.*;
command enter 의 최후 같군요. 수정하겠습니다 😭

2023-09-19 13:03 UTC, caoyu-dev commented
<img src="https://github.com/growth-ring/taskgrow/assets/73353809/c7ed182b-3d0b-4e6f-8a97-7c65bf0180c9" width="60%">

Swagger 를 통해 보여지는 API 문서에서의 데이터의 형식이 저희가 의도했던 방향대로 나타나고 있습니다. 
말씀주신 테스트 관련은 다음 PR 에서 전반적으로 정리하겠습니다.

2023-09-19 13:35 UTC, kyuwon53 approved these changes

2023-09-19 13:36 UTC, merged